# Generated by Django 3.0.8 on 2021-11-11 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('Adress', models.CharField(max_length=40, null=True)),
                ('Street', models.CharField(max_length=30, null=True)),
                ('PostalCode', models.BigIntegerField(null=True)),
                ('City', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParcelStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_c', models.CharField(blank=True, choices=[('Nadano', 'Nadano'), ('W drodze', 'W drodze'), ('Uszkodzona', 'Uszkodzona'), ('Zniszczona całkowicie', 'Zniszczona całkowicie'), ('Dostarczona', 'Dostarczona'), ('Błąd adresu', 'Błąd adresu'), ('Pozostawiona na magazynie', 'Pozostawiona na magazynie'), ('W trakcie wyjaśniania', 'W trakcie wyjaśniania')], default='Nadano', max_length=300, null=True)),
                ('status_details', models.CharField(blank=True, max_length=200, null=True)),
                ('dateStatus', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcelIDD', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('price', models.FloatField(null=True)),
                ('product', models.CharField(choices=[('Niestandardowa', 'Niestandardowa'), ('Standardowa', 'Standardowa')], max_length=200, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='parcelmanagement.Customer')),
                ('Sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='parcelmanagement.Customer')),
                ('status', models.ManyToManyField(related_name='parcelstatus', to='parcelmanagement.ParcelStatus')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
