# Generated by Django 3.0.8 on 2021-12-02 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcelmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Adress',
            new_name='EmailAdress',
        ),
    ]
