# Generated by Django 3.0.8 on 2021-12-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelmanagement', '0002_auto_20211202_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='EmailAdress',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='parcelstatus',
            name='status_c',
            field=models.CharField(choices=[('Nadano', 'Nadano'), ('W drodze', 'W drodze'), ('Uszkodzona', 'Uszkodzona'), ('Zniszczona całkowicie', 'Zniszczona całkowicie'), ('Dostarczona', 'Dostarczona'), ('Błąd adresu', 'Błąd adresu'), ('Pozostawiona w magazynie', 'Pozostawiona w magazynie'), ('W trakcie wyjaśniania', 'W trakcie wyjaśniania')], default='Nadano', max_length=300),
        ),
    ]
