# Generated by Django 3.0.8 on 2021-12-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelmanagement', '0003_auto_20211207_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='City',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='EmailAdress',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='PostalCode',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Street',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
