# Generated by Django 3.0.8 on 2021-12-10 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parcelmanagement', '0004_auto_20211209_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelstatus',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
