# Generated by Django 3.0.8 on 2021-12-10 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcelmanagement', '0005_auto_20211210_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcelstatus',
            name='author',
        ),
    ]
