# Generated by Django 3.0.8 on 2021-12-16 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcelmanagement', '0006_remove_parcelstatus_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcelstatus',
            options={'ordering': ('-dateStatus',)},
        ),
        migrations.AlterField(
            model_name='parcel',
            name='Receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiver', to='parcelmanagement.Customer'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='Sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sender', to='parcelmanagement.Customer'),
        ),
        migrations.AlterField(
            model_name='parcelstatus',
            name='status_c',
            field=models.CharField(choices=[('01:Nadano', '01:Nadano'), ('02:W drodze', '02:W drodze'), ('03:Uszkodzona', '03:Uszkodzona'), ('04:Zniszczona całkowicie', '04:Zniszczona całkowicie'), ('05:Dostarczona', '05:Dostarczona'), ('06:Błąd adresu', '06:Błąd adresu'), ('07:Pozostawiona w magazynie', '07:Pozostawiona w magazynie'), ('08:W trakcie wyjaśniania', '08:W trakcie wyjaśniania')], max_length=300),
        ),
        migrations.AlterField(
            model_name='parcelstatus',
            name='status_details',
            field=models.CharField(blank=True, default=0, max_length=200),
            preserve_default=False,
        ),
    ]
